### ISSUE TITLE
Error while attempting to bind on address...: address already in use

### ISSUE THREAD

**Issue by prokher** [Extremus-io/djwebsockets#1]
Hi!

The idea is clean and simple, but unfortunately I can not image how can it be used in production since in practice it is impossible to run multiple instances of django application with enabled djwebsockets. The reason is trivial. Each time we run wsgi app it tries to bind socket on `WEBSOCKET_HOST:WEBSOCKET_PORT`, so even second wsgi instance will not be able to do it.

**Comment by kittuov** [comment]
i agree. but currently if more than one instances are created, there is no way to communicate between the websockets created in those two instances, which is a serious problem. 

only solution is if we can create a websocket server in a different runtime and set a way for both of them to talk.

I was planning on doing this until my exams. i'll try to finish it in few days. if you can think of any other better solution, please let me know.

**Comment by kittuov** [comment]
@prokher I'm working on number of projects right now. also, i shifted the base of my main projects to golang. i cant work on this right now. any help would be greatly appreciated.

**Comment by prokher** [comment]
There is an alternative implementation to incorporate real-time capabilities in Django http://channels.readthedocs.org/en/latest/ it is under active development at the moment and, as I see, targets to be a part of next Django release.
