### ISSUE TITLE
【Question】

### ISSUE THREAD

**Issue by david30907d** [Extremus-io/djwebsockets#3]
Sorry for bothering you.
I have a stupid question, i've read your readme, but I don't know how to do this:
`add WEBSOCKET_HOST and WEBSOCKET_PORT to settings.py`

would you please give me a hint or some sample settings ?

Best regards

**Comment by d0d0** [comment]
Maybe this will help you

```
WEBSOCKET_HOST = 'localhost'
WEBSOCKET_PORT = 5000
```

with result
`Starting websocket server at ws://localhost:5000`

**Comment by david30907d** [comment]
Thanks a lot, very appreciate your answering

best regard
